// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuRV7RvOeQ-xAnYoRQUfmu1domjR8XAFg',
    appId: '1:914857856512:web:3b89762ea4fc785c43d2e5',
    messagingSenderId: '914857856512',
    projectId: 'curso-firebase-cd4a5',
    authDomain: 'curso-firebase-cd4a5.firebaseapp.com',
    storageBucket: 'curso-firebase-cd4a5.appspot.com',
    measurementId: 'G-V9K520Y835',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPYl3XuYDBo6iJB6-TBckjxOOdC8AFNMA',
    appId: '1:914857856512:android:2458669f9cdad9c343d2e5',
    messagingSenderId: '914857856512',
    projectId: 'curso-firebase-cd4a5',
    storageBucket: 'curso-firebase-cd4a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiJg60pdUmIlu_PY7UnktNc08rzEOirFw',
    appId: '1:914857856512:ios:62ca4b560aac646a43d2e5',
    messagingSenderId: '914857856512',
    projectId: 'curso-firebase-cd4a5',
    storageBucket: 'curso-firebase-cd4a5.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiJg60pdUmIlu_PY7UnktNc08rzEOirFw',
    appId: '1:914857856512:ios:62ca4b560aac646a43d2e5',
    messagingSenderId: '914857856512',
    projectId: 'curso-firebase-cd4a5',
    storageBucket: 'curso-firebase-cd4a5.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuRV7RvOeQ-xAnYoRQUfmu1domjR8XAFg',
    appId: '1:914857856512:web:6bb129e08871f72143d2e5',
    messagingSenderId: '914857856512',
    projectId: 'curso-firebase-cd4a5',
    authDomain: 'curso-firebase-cd4a5.firebaseapp.com',
    storageBucket: 'curso-firebase-cd4a5.appspot.com',
    measurementId: 'G-9NPGPB80XK',
  );

}